name: Run Gradle build
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        #jdk: [8,11,13]
        jdk: [8]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      # https://github.com/marketplace/actions/gradle-command
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
